<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        if(isset($_SESSION['user_logged'])){
            if ($_SESSION['user_logged'] == FALSE) {
            	 $this->session->set_flashdata('error','Please Login First To View This Page !');
    		redirect('auth/index');
            }
        }else{
            redirect('auth/index');
        }
        
    }

    function index()
    {
        $data['_view'] = 'dashboard';
        $this->load->view('layouts/main',$data);
    }
}
